### ISSUE TITLE
Scope naming scheme.

### ISSUE THREAD

**Issue by IO42630** [DurandA/ace#6]
https://github.com/DurandA/ace/blob/3b69e40b118cfab9d430a1730c0531ef7ddbd318/examples/temperature_server.py#L22

Is it feasible to change the scope naming scheme from:
`scope="read_temperature"`
to:
`scope="METHOD PATH"`
in order to match the location of the currently requested resource, such that scope becomes for example:
`scope="GET /temperature"`
`scope="PUT /0/properties/temperature"`
?

Pros:
+ RS can check scope without the necessity of an internal scope to PATH table.

Cons:
- Sending PATH over the air from CL to AS/authz-info might not in accordance ACE spec.

**Comment by DurandA** [comment]
[RFC 6749](https://tools.ietf.org/html/rfc6749#section-3.3) states the following:
> The value of the scope parameter is expressed as a list of space-delimited, case-sensitive strings. The strings are defined by the authorization server.

It does not violate the specs, but I would definitively say that this is a bad practice. If your goal is to get rid of the *wrap* function, I suggest to use [function decorators](https://www.python.org/dev/peps/pep-0318/) instead.

**Comment by IO42630** [comment]
Got it. Thank you.
